name: CI Test Trigger

on: [push, workflow_dispatch]

jobs:
  test_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World! The Actions tab is working!"
